title: DATA-621-Final-Project -- Determinants of Recurrent Stroke Incidence in a Clinical Sample


team_members:
  - name: Coco Donovan
    github: https://github.com/cocodono
  - name: Marjete Vucinaj
    github: https://github.com/MarjeteV
  - name: Jean Jimenez
    github: https://github.com/sleepysloth12
  - name: Matthew Roland
    github: https://github.com/Mattr5541

theme: minima


